name: WSA
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      runner:
        required: true
        type: string
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string

jobs:
  build-kernel-a15-6-6-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          - wsa_branch: "5.15.104.4"
            wsa_arch: "x86_64"
          - wsa_branch: "5.15.104.4"
            wsa_arch: "arm64"
    uses: ./.github/workflows/wsa-kernel.yml
    secrets: inherit
    with:
      android_version: "android13"
      kernel_version: "5.15"
      wsa_branch: ${{ matrix.wsa_branch }}
      wsa_arch: ${{ matrix.wsa_arch }}
      runner: ${{ inputs.runner }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}
